# -*- coding: utf-8 -*-
"""HPC_Mini_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nWs5mSsEgZhiifV2SZE2CSzhDFHIb4jC

Mini Project: Implement Parallelization of Database Query optimization
"""

import multiprocessing, random, time

def generate_query_plans():
    tables=['tableA','tableB','tableC','tableD']
    columns=['columnA','columnB','columnC','columnD']
    join=['INNER JOIN','LEFT JOIN','RIGHT JOIN']
    op=['=','>','<','>=','<=','<>']

    query_plans=[]
    for _ in range(10):
        t=random.sample(tables,2)
        c=random.sample(columns,2)

        query=f"SELECT {c[0]}, {c[1]} FROM {t[0]} {random.choice(join)} {t[1]} ON {c[0]}={c[1]}"
        query+=f" WHERE {c[0]} {random.choice(op)} {random.randint(1,100)}"

        query_plans.append(query)

    return query_plans

def optimize_query(q):
    time.sleep(random.random())
    return (q, random.random())

def optimize_queries_parallel(plans):
    pool=multiprocessing.Pool()
    res=pool.map(optimize_query,plans)
    pool.close()
    pool.join()
    res.sort(key=lambda x:x[1])
    return res[0][0]

if __name__=="__main__":
    plans=generate_query_plans()

    print("Query plans:")
    for q in plans:
        print(q)

    best=optimize_queries_parallel(plans)

    print("\nOptimized query:",best)

!jupyter  nbconvert --to html "/content/HPC_Mini_Project.ipynb"